"use server"

import { generate } from "@/lib/actions/generate/generate";

export const generateService = async (description: string, about: string) => {

    const paragraphText = await generate("Ciaran Bohan is a Civil Engineer and Project Manager with over 17 years’ experience in the Building");
    const serviceContent = JSON.stringify([{"id":"4867","type":"HeaderTwo","extraAttributes":{"image":"https://julftz3s2fuspgpn.public.blob.vercel-storage.com/4WufbkDZ_wGUoeRyQqCHl-aRYcb7Zu4sHUqzZDryL8nvfysCLih6.png","backgroundColour":"#ffe59b","tagline":{"text":"SERVICE DETAILS","textColour":"#0c353d"},"title":{"text":"Retrofitting","textColour":"#0c353d"},"paragraph":{"text":"Application of Internal Wall Insulation and Roof Insulation to houses as a standalone service or as part of a deeper retrofit project. We are registered to facilitate the application for Better Energy Homes grants from SEAI.\n\n","textColour":"#0c353d"},"button":{"text":"Contact Our Team","textColour":"#ffffff","link":"contact","backgroundColour":"#0c353d"}}},{"id":"8563","type":"TextTwo","extraAttributes":{"backgroundColour":"#FFFFFF","longText":{"text":"Welcome to our comprehensive insulation services tailored for homeowners – specializing in Internal Wall and Roof Insulation. Whether you're considering these upgrades as standalone improvements or as integral components of a more extensive retrofit project, we're here to meet your needs.\n‍\nOur core focus is on elevating the energy efficiency and comfort of your residence through expert insulation solutions. We're not just in the business of applying insulation; we're committed to transforming your living space into an environment that's both eco-friendly and economical.\n‍\nIn recognition of our expertise, we're proud to be registered facilitators for Better Energy Homes grants from SEAI. This means that not only can you enhance your home's energy efficiency, but you can also potentially benefit from financial support to make your investment even more advantageous. Thank you for considering us as your partner in realizing a more sustainable, comfortable, and cost-effective home.","textColour":"#616161"},"linksTitle":{"text":"Contact Us","textColour":"#FFFFFF"},"linksBackgroundColour":"#333333","linksColour":"#FFFFFF","links":[{"title":"ciaranb17@yahoo.com","link":"ciaranb17@yahoo.com","key":"1079"},{"title":"0873883357","link":"0873883357","key":"4716"},{"title":"Galway, Ireland","link":"/","key":"7899"}]}}]);

    return serviceContent;
}
