"use server"

import { generate } from "@/lib/actions/generate/generate";

export const generateServicesPage = async (description: string, about: string) => {

    const paragraphText = await generate("Ciaran Bohan is a Civil Engineer and Project Manager with over 17 years’ experience in the Building");
    const servicesContent = JSON.stringify([{"id":"5516","type":"HeroOne","extraAttributes":{"image":"https://julftz3s2fuspgpn.public.blob.vercel-storage.com/uzDY2qzItE28k6GFQTUyL-xVsvrswqBuF6CiBfBHKX85cuP8ATp2.png","backgroundColour":"#ffe59b","tagline":{"text":"CIARAN BOHAN CONSTRUCTION LTD.","textColour":"#0d343d"},"title":{"text":"Construction & Civil Engineering","textColour":"#0d343d"},"paragraph":{"text": paragraphText,"textColour":"#0d343d"},"button":{"text":"Contact Our Team","textColour":"#FFFFFF","link":"contact","backgroundColour":"#0d343d"}}},{"id":"3103","type":"ContentOne","extraAttributes":{"image":"https://julftz3s2fuspgpn.public.blob.vercel-storage.com/ov10NVFO1lGIyD4BggWDK-gvz69DUlEzug0RZP0AgNOiyum9wZ6f.png","backgroundColour":"#FFFFFF","tagline":{"text":"CIARAN BOHAN CONSTRUCTION LTD.","textColour":"#0c353d"},"title":{"text":"Committed to Providing Exceptional Client Service","textColour":"#0c353d"},"paragraph":{"text":"Ciaran Bohan is a Civil Engineer and Project Manager with over 17 years’ experience in the Building and Civil Engineering industry, having worked on large scale construction projects as head senior engineer and project manager. Registered as a BER Assessor in 2020, he has now completed over 350 assessments around the country.","textColour":"#0c353d"},"button":{"text":"About Us","textColour":"#FFFFFF","link":"about","backgroundColour":"#0c353d"}}},{"id":"614","type":"CollectionOne","extraAttributes":{"backgroundColour":"#ffe59b","tagline":{"text":"CONSTRUCTION EXPERTISE","textColour":"#0c353d"},"title":{"text":"Our Services","textColour":"#0c353d"},"paragraph":{"text":"Specialists in sustainable infrastructure, urban development, and project management with a commitment to quality and innovation.","textColour":"#0c353d"}}},{"id":"5855","type":"ActionOne","extraAttributes":{"image":"https://julftz3s2fuspgpn.public.blob.vercel-storage.com/-iaG03FXS76f5buhhFRE0-QXsXbKZ6qGp1iUb6302u4rAfqU4lE4.png","backgroundColour":"#FFFFFF","title":{"text":"Have a question? Get in touch with our team.","textColour":"#FFFFFF"},"button":{"text":"Contact Our Team","textColour":"#FFFFFF","link":"contact","backgroundColour":"#0c353d"}}}]);

    return servicesContent;
}
